src/ring/adapter/jetty9.clj
Specifically, adds the ability to specify a bounded queue to back the thread pool, as suggested by https://wiki.eclipse.org/Jetty/Howto/High_Load#Thread_Pool
Uses the minThreads and idleTimeout values specified by the existing QueuedThreadPool constructors: https://github.com/eclipse/jetty.project/blob/a3201a3c810da37ad892e62c1f04600dc889d14a/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java#L70-L78
=> Allow more threadpool configuration

project.clj
See https://github.com/eclipse/jetty.project/blob/cfca172dd68846b2c7f30a9a6b855f08da7e7946/advisories/2015-02-24-httpparser-error-buffer-bleed.md for details.
=> Upgrade jetty versions for security upgrade

README.md, src/ring/adapter/jetty9.clj
Jetty forces a trailing slash to the end of URLs, as mentioned in this project's README.md. This is achieved via a redirect and some browsers will fail to establish the WebSocket connection if this redirect is received.
This change allows Jetty's redirect to be disabled by setting `:allow-null-path-info true`. WebSocket connections can then be established with or without a trailing slash, and Jetty will not redirect.
=> Add flag to allow 'ensure trailing slash' behaviour to be disabled

src/ring/adapter/jetty9.clj
Currently, it is not possible to call `run-jetty` without always running a HTTP connector. 
To have parity with the official `ring-jetty-adapter`, I have added a `http?` flag, which gives you the ability to only run an SSL HTTP connector - if that's what you desire.
=> Add :http? flag

src/ring/adapter/jetty9.clj
See http://www.eclipse.org/jetty/documentation/9.4.x/configuring-connectors.html#_proxy_protocol
In particular this allows jetty9 to receive requests from an [AWS ELB with the proxy protocol enabled](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html). This configuration then allows jetty to understand the correct remote (client) address even when serving websocket requests via an ELB.
=> Add support for proxy protocol

src/ring/adapter/jetty9.clj, src/ring/adapter/jetty9/common.clj, src/ring/adapter/jetty9/websocket.clj
Currently the ws-creator-fn is able to return an error object with status and message if it decides that the WebSocket should not be established. This change allows the ws-creator-fn to also include a `:headers` key in the returned error object, so that the error response has additional headers.
The `set-headers` function was taken from [ring-servlet](https://github.com/ring-clojure/ring/blob/6be2fc28195c6347c1394f44619325bc77e633fe/ring-servlet/src/ring/util/servlet.clj#L69). I opted to copy the code rather than refer to a private var.
=> Allow headers to be added to error response

project.clj, src/ring/adapter/jetty9.clj
Add alpn-server for OpenJDK8 and reorder ciphers and protocols so that http/2 is preferred.
=> Fix #36 making http2 work again

src/ring/adapter/jetty9.clj
Fixes #39 
* pass `:thread-pool` to `run-jetty` to use a customized thread pool
* pass `:wrap-handler` to `run-jetty` to provide a handler wrapper function that takes default r9ja jetty handler and return a new one
=> Allow customizing thread pool and handler

src/ring/adapter/jetty9.clj, src/ring/adapter/jetty9/websocket.clj
Hi,
I propose to add a new option `:ws-max-text-message-size`, which makes it possible to set `max-text-message-size` for web socket handler.
=> Support set max-text-message-size for web socket

examples/rj9a/websocket_upgrade.clj, src/ring/adapter/jetty9.clj, src/ring/adapter/jetty9/common.clj, src/ring/adapter/jetty9/websocket.clj
A ring handler can detect a websocket protocol upgrade request by inspecting the `Connection` and `Upgrade` headers. Then the ring handler may decide to proceed with the upgrade by returning HTTP status 101 (Switching Protocols) with the appropriate websocket upgrade response headers. Then the ring adapter automatically upgrades the HTTP request to a websocket connection. In this case the ring adapter expects the response map to have a `:ws` key containing the websocket handler.
The motivation here is to allow clients to connect on the same URI path for regular HTTP calls as well as websockets. E.g. GraphQL clients typically connect on the same URI path (e.g. `/graphql`) for running queries and making subscriptions over websocket.
Two unresolved issues in this PR:
* …
=> Add support for websocket protocol upgrade.

.github/workflows/clojure.yml, README.md, dev-resources/simplelogger.properties, examples/rj9a/http3.clj, http3/.gitignore, http3/project.clj, http3/src/ring/adapter/jetty9/http3.clj, project.clj, src/ring/adapter/jetty9.clj
Tasks before merging this:
Fixes #68
=> feat: implement http3 connector

project.clj, src/ring/adapter/jetty9.clj, src/ring/adapter/jetty9/common.clj, src/ring/adapter/jetty9/servlet.clj, src/ring/adapter/jetty9/websocket.clj
This migrates the code over to Jetty 11. The javax.servlet package is renamed to jakarta.servlet in Jetty 11. To support this, the ring.util.servlet dependency is removed (which imports the deprecated javax.servlet package), and the required code is copied over into ring.adapter.jetty9.servlet.
=> Jetty 11 Support

examples/rj9a/websocket.clj, src/ring/adapter/jetty9/websocket.clj
Fixes #79 
`:extensions` from websocket handshake handler result was suffering a type issue, that we treated `JettyExtensionConfig` from `UpgradeRequest` as string. In this patch we supported both string and `JettyExtensionConfig` so that user can either forward it from request map, or create their own as string.
=> fix: allow both string and ExtensionConfig for :extensions

src/ring/adapter/jetty9.clj, src/ring/adapter/jetty9/servlet.clj
Just some small metadata changes that should remove the reliance on runtime reflection for this library to work. This should allow a project using HTTPS and GraalVM to stick to the publicly known reachability metadata - https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/org.eclipse.jetty/jetty-server/11.0.12
=> fix: correct/add type hints to avoid reflection

src/ring/adapter/jetty9.clj
Fixes #85 
If `ssl?` is specifies, we provide default value `443` to `ssl-port`
=> fix: add default value for ssl-port if ssl? enabled

src/ring/adapter/jetty9.clj, test/ring/adapter/jetty9_test.clj
=> Rework the ssl-hot-reload-loop lifecycle, and revert return-type change in `run-jetty`

src/ring/adapter/jetty9.clj, test/ring/adapter/jetty9_test.clj
Add configuration for http2 connection factory.
As a map under :h2-options key in top level run-jetty config.
At the moment all options from [AbstractHTTP2ServerConnectionFactory](https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.html), cause not sure which specific could be useful for an audience. Maybe it makes sense to keep only some of them.
Two of the options take java Objects as arg (FlowControlStrategy$Factory and RateControl$Factory), don't think it's worth to make wrappers.
Default values for options are leaved to Jetty.
Didn't tested yet, let's discuss general form and list of options for now.
=> Http2 options

src/ring/adapter/jetty9/handlers/async.clj, src/ring/adapter/jetty9/handlers/sync.clj, test/ring/adapter/jetty9_test.clj
Fixes #102 
This patch allows us to use var for handler so such we can reload handler without restart the server.
=> feat: accept var as handler

project.clj, src/ring/adapter/jetty9.clj, src/ring/adapter/jetty9/handlers/sync.clj, src/ring/adapter/jetty9/websocket.clj
This patch is to add back websocket api fully based on jetty-core of jetty 12
=> feat: Implement jetty-core based websocket api for jetty 12

project.clj, src/ring/adapter/jetty9.clj, src/ring/adapter/jetty9/handlers/async.clj
This patch enables async ring handlers on jetty 12.
We still have a TODO here is for lack of `async-timeout` support on pure jetty APIs. If we really want to port that functionality, we will need to maintain a scheduler by ourself and schedule a task to track it.
=> feat: port aysnc ring handler

src/ring/adapter/jetty9/common.clj
when looking at request maps, found a bug with character encoding
=> fix: character encoding was previously returning content-type

http3/project.clj, project.clj, src/ring/adapter/jetty9.clj, src/ring/adapter/jetty9/common.clj, src/ring/adapter/jetty9/handlers/async.clj, src/ring/adapter/jetty9/handlers/sync.clj
This patch upgrades Jetty to 12.0.2 and bring in improvements on Buffer outputstream in https://github.com/eclipse/jetty.project/issues/10476
=> feat: upgrade jetty to 12.0.2 and improve buffered output stream

http3/project.clj, project.clj, src/ring/adapter/jetty9/common.clj
Upgraded jetty to 12.0.4 and adopt changes about `SecureRequestCustomizer` in https://github.com/jetty/jetty.project/pull/10853
=> feat: jetty 12.0.4

README.md, examples/rj9a/websocket.clj, src/ring/adapter/jetty9/websocket.clj
This patch updates:
- Our ring.websocket.protocol implementation based on feedback from @weavejester
- Websocket example to use latest ring.websocket apis
- README for new ring.websocket usage
=> fix: ring websocket implementation fix

project.clj, src/ring/adapter/jetty9/handlers/sync.clj
It provides information about original eception in case when response channel was already closed ( we just had it in http2 communication)
In this scenario message from original exception is lost because jetty in sendError throws new IllegalStateException whenever output channel is not open.
=> debug logging of internal exception in case response can not be sent to client

src/ring/adapter/jetty9.clj, src/ring/adapter/jetty9/websocket.clj
Fixes #124 
Added options to configure max frame size and max binary message size. Note that this patch also changed default value of `ws-max-idle-time` to default value of jetty: 30s.
=> feat: add more options for websocket

http3/project.clj, http3/src/ring/adapter/jetty9/http3.clj, project.clj, src/ring/adapter/jetty9.clj, test/ring/adapter/jetty9_test.clj
The original `Http3ServerConnector` has been deprecated. This patch upgrades `http3` module to latest api. The user-facing api of rj9a remains unchanged.
=> feat: upgarde http3 module to latest QuicServerConnector api

.gitignore, src/ring/adapter/jetty9/common.clj
Fixes #136.
Changes the `get-headers` function to merge multiple cookie fields into one field; make the behavior consistent with HTTP/1.1 headers. Also added `.lsp` and `.clj-kondo` to gitignore.
=> feat: support http2 request headers that contains multiple cookie fields

src/ring/adapter/jetty9/handlers/sync.clj
Fixes #146 
This patch removes global try-catch in our handler. It enables `:wrap-jetty-handler` to do exception inception.
=> feat: remove global try-catch in handler

src/ring/adapter/jetty9/handlers/async.clj
Keep our error processing consistent.
=> fix: remove auto error handle in async handler

http3/src/ring/adapter/jetty9/http3.clj, src/ring/adapter/jetty9.clj, src/ring/adapter/jetty9/common.clj
Fixes #161 
This patch included all http configuration items from latest jetty release. It also refactors how we implement the configuration generation. We no longer provide default values in our codebase.
=> feat: update http configuration 
