sunng87/ring-jetty9-adapter

- examples/rj9a/websocket.clj
- src/ring/adapter/jetty9/common.clj
- src/ring/adapter/jetty9/websocket.clj
> (feat) build request map from upgrade request

- README.md
- examples/rj9a/websocket.clj
- src/ring/adapter/jetty9/websocket.clj
> (feat) subprotocol and extension negotiation support [#47]

- README.md
- examples/rj9a/websocket.clj
- src/ring/adapter/jetty9.clj
- src/ring/adapter/jetty9/websocket.clj
I had a need for this and saw that there was some question about how best to handle it in the comments.
> Adds support for ping/pong listener, and a `ping!` fn

- src/ring/adapter/jetty9.clj
- src/ring/adapter/jetty9/common.clj
- src/ring/adapter/jetty9/websocket.clj
And remove unused functions.
Fixes #61
> Fix websocket upgrade on Firefox.

- examples/rj9a/http2.clj
- src/ring/adapter/jetty9.clj
> feat: add support for sni-required and sni-host-check

- src/ring/adapter/jetty9/websocket.clj
> fix: multi-arity implementation of close!

- src/ring/adapter/jetty9.clj
I was hoping that supporting the `:async-timeout` option that the original `ring-jetty-adapter` supports would be possible. Thanks!
The choices for the default value that were most apparent to me were the following:
- `0` to match the expectations of migrating users
- `30000` to match current behavior and expectations of existing users
I leaned toward `30000` for the following reasons:
- It avoids a breaking change
- `0` would mean an unbounded timeout, which I feel is not a good default
- [Usage in `ring-jetty-adapter`](https://github.com/ring-clojure/ring/blob/8af4ab93190dfe5b4827c14b416a4cb92e18cdaf/ring-jetty-adapter/src/ring/adapter/jetty.clj#L54)
- [`ring.adapter.jetty/run-jetty`: "defaults to 0, no timeout"](https://github.com/ring-clojure/ring/blob/8af4ab93190dfe5b4827c14b416a4cb92 …
> Support the :async-timeout option

- project.clj
- src/ring/adapter/jetty9.clj
- src/ring/adapter/jetty9/common.clj
- src/ring/adapter/jetty9/handlers/async.clj
- src/ring/adapter/jetty9/handlers/sync.clj
- src/ring/adapter/jetty9/servlet.clj
- src/ring/adapter/jetty9/websocket.clj
> use `gen-class` for proxying handlers

- src/ring/adapter/jetty9.clj
- src/ring/adapter/jetty9/common.clj
It turns out that jetty already has support for this in the `KeystoreScanner` class!
> refactor!: rework/simplify implementation of SSL keystore hot-reload

- src/ring/adapter/jetty9/websocket.clj
Update the doc-string to describe the expected arguments
> Update doc-string for ws-upgrade-response in websocket.clj

- http3/src/ring/adapter/jetty9/http3.clj
- src/ring/adapter/jetty9.clj
- test/ring/adapter/jetty9_test.clj
Key name is `:http3-options` to mirror existing `:http3?`
> Add configuration for quic and http3

- project.clj
- src/ring/adapter/jetty9.clj
- src/ring/adapter/jetty9/handlers/sync.clj
- src/ring/adapter/jetty9/websocket.clj
Reverts sunng87/ring-jetty9-adapter#107
> Revert "feat: Implement jetty-core based websocket api for jetty 12"

- src/ring/adapter/jetty9/common.clj
I did try to profile your code...  but profiler output that I was seeing looked incorrect, so I couldn't get profile guided optimizations.... 
I tried to optimize in the dark, and none of this code really improved throughput, but if you want it anyways, it's still logical changes... but no worries if you don't want it.
> refactor(common): potentially avoid reflection

- src/ring/adapter/jetty9.clj
Add a dedicated option to enable virtual threads support for thread pool created by our adapter.
> feat: add option  to enable virtual threads support for thread pool

- examples/rj9a/websocket.clj
- project.clj
- src/ring/adapter/jetty9.clj
- src/ring/adapter/jetty9/common.clj
- src/ring/adapter/jetty9/handlers/async.clj
- src/ring/adapter/jetty9/handlers/sync.clj
- src/ring/adapter/jetty9/websocket.clj
- test/ring/adapter/jetty9_test.clj
This patch tracks #115 to migrate our websocket API to Ring's newly added websocket spec.
> feat: proof of concept implementation for ring.websocket

- src/ring/adapter/jetty9.clj
- test/ring/adapter/jetty9_test.clj
> fix: add back wrap jetty handler

- http3/project.clj
- project.clj
- Remove dependency to ring-core
- Add dependency to ring-core-protocols
- Add log impl to examples
> feat: update ring to 1.12

- examples/rj9a/websocket.clj
- project.clj
- src/ring/adapter/jetty9/websocket.clj
> fix: correct check for websocket ping implementation

- src/ring/adapter/jetty9/handlers/async.clj
> fix: return true with async handler

- .github/workflows/clojure.yml
- http3/src/ring/adapter/jetty9/http3.clj
- src/ring/adapter/jetty9.clj
- src/ring/adapter/jetty9/common.clj
- src/ring/adapter/jetty9/websocket.clj
> chore: lint and add ci

- http2/project.clj
- http3/project.clj
- project.clj
Upgrade jetty to latest release
> feat: jetty 12.0.20

- http2/project.clj
- http3/project.clj
- project.clj
update jetty to latest 12.0.25 release
> feat: jetty 12.0.25
